# Stage 1: Build
FROM node:16-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ./src ./src
COPY tsconfig.build.json tsconfig.build.json
COPY tsconfig.json tsconfig.json

RUN npm run build

# Stage 2: Run
FROM node:16-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

ENV DATABASE_URL=mongodb://localhost:27017/blog
ENV DATABASE_URL_TEST=mongodb://localhost:27017/blog-test
ENV PORT_API=3001
ENV NODE_ENV=DEV
ENV OWNER_KEY=suaSenha
ENV JWT_SECRET=seuJwtSecret

EXPOSE 3001

CMD ["node", "dist/main"]
