on: [pull_request]

jobs:
  eslint-api:
    runs-on: ubuntu-20.04
    steps:
      - name: Verify Git Repository
        uses: actions/checkout@v2

      - name: Install node with the version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Installing dependencies
        run: npm install

      - name: Running lint to check errors
        run: npm run lint:check

  test-e2e:
    runs-on: ubuntu-20.04
    needs: [eslint-api]
    steps:
      - name: Verify Git Repository
        uses: actions/checkout@v2

      - name: Create image 
        run: docker build . -t blog-api-test -f Dockerfile.test

      - name: Run containers
        run: docker run --name blog-api blog-api-test

      - name: Derruba o container
        if: always()
        run: docker rm --force blog-api
